packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/config/*'

catalog:
  eslint: ^9.35.0
  oxlint: ^1.16.0
  prettier: ^3.6.2
  nuxt: ^4.1.2
  vue: ^3.5.21
  vue-router: ^4.5.1
# minimumReleaseAge: 1440 # 1 day
